development:
  adapter: sqlite3
  database: db/community_poll_hub.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/community_poll_hub_test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/community_poll_hub_production.sqlite3
  pool: 5
  timeout: 5000 